copr_repositories:
  - agriffis/neovim-nightly

packages:
  core:
    - ansible
    - git
    - python3
    - python3-pip

  editors:
    - neovim

  development:
    - nodejs
    - golang
    - rust
    - python

  desktop:
    - rofi
    - picom

teardown_packages:
  core:
    - ansible
    - python3-pip
    - git

  editors:
    - neovim

  development:
    - nodejs
    - golang
    - rust
    - python

  desktop:
    - rofi
    - picom
