---
- name: Gather initial facts
  hosts: localhost
  gather_facts: true
  become: false
  tasks:
    - name: Store the actual user
      ansible.builtin.set_fact:
        actual_user: "{{ ansible_user_id }}"
        actual_user_home: "{{ ansible_user_dir }}"

- name: Teardown Fedora Dev Environment
  hosts: localhost
  become: true
  vars_files:
    - packages.yml

  tasks:
    - name: Symlink Cleanup
      block:
        - name: Remove nvim symlink
          ansible.builtin.file:
            path: "{{ actual_user_home }}/.config/nvim"
            state: absent

        - name: Remove .zshrc
          block:
            - name: Remove .zshrc symlink
              ansible.builtin.file:
                path: "{{ actual_user_home }}/.zshrc"
                state: absent

            - name: Remove .zshrc.bak
              ansible.builtin.file:
                path: "{{ actual_user_home }}/.zshrc.bak"
                state: absent

            - name: Remove .zsh_scripts
              ansible.builtin.file:
                path: "{{ actual_user_home }}/.zsh_scripts"
                state: absent

        - name: Remove .p10k
          ansible.builtin.file:
            path: "{{ actual_user_home }}/.p10k.zsh"
            state: absent

        - name: Remove tmux config
          block:
            - name: Remove .tmux.conf
              ansible.builtin.file:
                path: "{{ actual_user_home }}/.tmux.conf"
                state: absent

            - name: Remove .tmux-themepack
              ansible.builtin.file:
                path: "{{ actual_user_home }}/.tmux-themepack"
                state: absent

    - name: Directory Cleanup
      block:
        - name: Remove oh-my-zsh dir
          ansible.builtin.file:
            path: "{{ actual_user_home }}/.oh-my-zsh"
            state: absent

        - name: Remove .local/share/nvim
          ansible.builtin.file:
            path: "{{ actual_user_home }}/.local/share/nvim"
            state: absent

        - name: Remove powerlevel10k
          ansible.builtin.file:
            path: "{{ actual_user_home }}/powerlevel10k"
            state: absent

        - name: Remove fonts
          become: true
          become_user: "{{ actual_user }}"
          block:
            - name: Remove .local/share/fonts
              ansible.builtin.file:
                path: "{{ actual_user_home }}/.local/share/fonts"
                state: absent
            - name: Update font cache after removal
              ansible.builtin.command:
                cmd: fc-cache -f
              changed_when: true

    - name: Environment Cleanup
      become: true
      block:
        - name: Reset shell to bash
          ansible.builtin.user:
            name: "{{ actual_user }}"
            shell: /usr/bin/bash

    - name: Package Removal
      block:
        - name: Remove desktop packages
          ansible.builtin.dnf:
            name: "{{ teardown_packages.desktop }}"
            state: absent

        # - name: Remove development packages
        #   ansible.builtin.dnf:
        #     name: "{{ teardown_packages.development }}"
        #     state: absent

        - name: Remove editor packages
          ansible.builtin.dnf:
            name: "{{ teardown_packages.editors }}"
            state: absent

        - name: Remove safe core packages
          ansible.builtin.dnf:
            name: "{{ teardown_packages.core }}"
            state: absent

    - name: Repository Cleanup
      block:
        # - name: Disable COPR repositories
        #   community.general.copr:
        #     name: "{{ item }}"
        #     state: disabled
        #   loop: "{{ copr_repositories }}"

        - name: Autoremove orphaned packages
          ansible.builtin.dnf:
            autoremove: true
