---
- name: Gather initial facts
  hosts: localhost
  gather_facts: true
  become: false
  tasks:
    - name: Store the actual user
      ansible.builtin.set_fact:
        actual_user: "{{ ansible_user_id }}"
        actual_user_home: "{{ ansible_user_dir }}"

- name: Teardown Fedora Dev Environment
  hosts: localhost
  become: true
  vars_files:
    - packages.yml

  tasks:
    - name: Package Removal
      block:
        - name: Remove desktop packages
          ansible.builtin.dnf:
            name: "{{ teardown_packages.desktop }}"
            state: absent

        # - name: Remove development packages
        #   ansible.builtin.dnf:
        #     name: "{{ teardown_packages.development }}"
        #     state: absent

        - name: Remove editor packages
          ansible.builtin.dnf:
            name: "{{ teardown_packages.editors }}"
            state: absent

        - name: Remove safe core packages
          ansible.builtin.dnf:
            name: "{{ teardown_packages.core }}"
            state: absent

    - name: Repository Cleanup
      block:
        # - name: Disable COPR repositories
        #   community.general.copr:
        #     name: "{{ item }}"
        #     state: disabled
        #   loop: "{{ copr_repositories }}"

        - name: Autoremove orphaned packages
          ansible.builtin.dnf:
            autoremove: true

    - name: Directory Cleanup
      block:
        - name: Remove Projects directory
          ansible.builtin.file:
            path: "{{ actual_user_home }}/Projects"
            state: absent
        - name: Remove nvim directory
          ansible.builtin.file:
            path: "{{ actual_user_home }}/.config/nvim"
            state: absent
